linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/qlcchain/qlc-go-sdk
  golint:
    min-confidence: 0
  lll:
    line-length: 140
  maligned:
    suggest-new: true
  misspell:
    locale: US

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

  # don't enable:
  # - gochecknoglobals
  # - gocognit
  # - godox
  # - maligned
  # - prealloc
  # - gochecknoinits

run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 30m
  skip-dirs:
    - autogenerated_by_my_lib
  skip-files:
    - ".*\\.my\\.go$"
    - "\\w+_gen.go$"
    - edwards25519.go

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - lll
        - gochecknoinits
        - gocyclo
        - funlen
