before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
  - id: robot-example-x64
    main: ./example/robot/main.go
    binary: qlcrobot
    env:
      - CGO_ENABLED=0
    ldflags:
      - main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"

