name: Main workflow
on: [push, pull_request]

jobs:
  build:
    name: Check, Build and Publish snapshot artifacts
    runs-on: ubuntu-18.04
    if: contains(github.event.head_commit.message, '[skip ci]') == false && contains(github.event.head_commit.message, '[ci skip]') == false

    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
        with:
          fetch-depth: 10

      - name: Check code style and calculate coverage
        env:
          GO111MODULE: "on"
        run: |
          if [[ -n "$(gofmt -l .| grep -v ^vendor/)" ]]; then
            echo "Go code is not formatted:"
            gofmt -d .
            exit 1
          fi
          go vet ./...
          go test ./... -covermode=atomic -coverprofile=coverage.txt
          make clean build

      - name: Upload codecov coverage
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella
  
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
        with:
          fetch-depth: 2

      - name: Run golangci-lint with reviewdog
        uses: reviewdog/action-golangci-lint@v1.1.7
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          golangci_lint_flags: "--config=./.golangci.yml"
