name: Reivew
on: [pull_request]

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
        with:
          fetch-depth: 2

      - name: Run golangci-lint with reviewdog
        uses: reviewdog/action-golangci-lint@v1.1.7
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          golangci_lint_flags: "--config=./.golangci.yml"
          level: warning 
          reporter: "github-pr-review"
